#define WINDOW_WIDTH          1600
#define WINDOW_HEIGHT         900
#define PLAYER_SPEED          500
#define LASER_SPEED           600
#define STAR_SPEED            100
#define METEOR_TIMER_DURATION 0.4
#define FONT_SIZE             30
#define NUMBER_OF_STARS       50
#define MAX_LIVES             3
#define MAX_SCORE             9999
#define EXPLOSION_SPEED       1500
