#define PLAYER_SPEED                 500
#define LASER_SPEED                  600
#define STAR_SPEED                   100
#define OPPONENT_SPEED               200
#define EXPLOSION_SPEED              1500
#define METEOR_TIMER_DURATION        0.4
#define OPPONENT_TIMER_DURATION      2
#define DISPERSION_TIMER_DURATION    31
#define INVINCIBILITY_TIMER_DURATION 41
#define EXTRALIFE_TIMER_DURATION     37
#define STAT_FONTSIZE                30
#define GAME_OVER_FONTSIZE           200
#define GAME_TITLE_FONTSIZE          120
#define SETTINGS_FONTSIZE            20
#define MENU_ITEM_FONTSIZE           40
#define NUMBER_OF_STARS              50
#define MAX_LIVES                    3
